### ISSUE TITLE
Handle zero values

### ISSUE THREAD

**Issue by aikikode** [kashesandr/CIC#3]
When adding people who didn't pay a cent (value = 0) they are ignored in the result.

E.g. input values are:
Dimitri: 50
Peter: 40
Ann: 30
Tom: 0

Current result:
Ann gives 10.00 to Dimitri

Expected result:
Tom gives 10.00 to Peter
Tom gives 20.00 to Dimitri

**Comment by kashesandr** [comment]
Thank you!

Fixed with the commit https://github.com/kashesandr/CIC/commit/24fc971a62993df4a3dc466cfc4f6bc01dcefa42
